/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthImport } from './routes/_auth'
import { Route as AppImport } from './routes/_app'
import { Route as AppIndexImport } from './routes/_app/index'
import { Route as AuthLoginImport } from './routes/_auth/login'
import { Route as AppVirtualAccountsImport } from './routes/_app/virtual-accounts'
import { Route as AppBankTransferImport } from './routes/_app/bank-transfer'
import { Route as AppIcodsaReceiptImport } from './routes/_app/icodsa/receipt'
import { Route as AppIcodsaLoaImport } from './routes/_app/icodsa/loa'
import { Route as AppIcodsaInvoiceImport } from './routes/_app/icodsa/invoice'
import { Route as AppIcicytaReceiptImport } from './routes/_app/icicyta/receipt'
import { Route as AppIcicytaLoaImport } from './routes/_app/icicyta/loa'
import { Route as AppIcicytaInvoiceImport } from './routes/_app/icicyta/invoice'

// Create/Update Routes

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const AppRoute = AppImport.update({
  id: '/_app',
  getParentRoute: () => rootRoute,
} as any)

const AppIndexRoute = AppIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)

const AppVirtualAccountsRoute = AppVirtualAccountsImport.update({
  id: '/virtual-accounts',
  path: '/virtual-accounts',
  getParentRoute: () => AppRoute,
} as any)

const AppBankTransferRoute = AppBankTransferImport.update({
  id: '/bank-transfer',
  path: '/bank-transfer',
  getParentRoute: () => AppRoute,
} as any)

const AppIcodsaReceiptRoute = AppIcodsaReceiptImport.update({
  id: '/icodsa/receipt',
  path: '/icodsa/receipt',
  getParentRoute: () => AppRoute,
} as any)

const AppIcodsaLoaRoute = AppIcodsaLoaImport.update({
  id: '/icodsa/loa',
  path: '/icodsa/loa',
  getParentRoute: () => AppRoute,
} as any)

const AppIcodsaInvoiceRoute = AppIcodsaInvoiceImport.update({
  id: '/icodsa/invoice',
  path: '/icodsa/invoice',
  getParentRoute: () => AppRoute,
} as any)

const AppIcicytaReceiptRoute = AppIcicytaReceiptImport.update({
  id: '/icicyta/receipt',
  path: '/icicyta/receipt',
  getParentRoute: () => AppRoute,
} as any)

const AppIcicytaLoaRoute = AppIcicytaLoaImport.update({
  id: '/icicyta/loa',
  path: '/icicyta/loa',
  getParentRoute: () => AppRoute,
} as any)

const AppIcicytaInvoiceRoute = AppIcicytaInvoiceImport.update({
  id: '/icicyta/invoice',
  path: '/icicyta/invoice',
  getParentRoute: () => AppRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_app/bank-transfer': {
      id: '/_app/bank-transfer'
      path: '/bank-transfer'
      fullPath: '/bank-transfer'
      preLoaderRoute: typeof AppBankTransferImport
      parentRoute: typeof AppImport
    }
    '/_app/virtual-accounts': {
      id: '/_app/virtual-accounts'
      path: '/virtual-accounts'
      fullPath: '/virtual-accounts'
      preLoaderRoute: typeof AppVirtualAccountsImport
      parentRoute: typeof AppImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof AuthImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/icicyta/invoice': {
      id: '/_app/icicyta/invoice'
      path: '/icicyta/invoice'
      fullPath: '/icicyta/invoice'
      preLoaderRoute: typeof AppIcicytaInvoiceImport
      parentRoute: typeof AppImport
    }
    '/_app/icicyta/loa': {
      id: '/_app/icicyta/loa'
      path: '/icicyta/loa'
      fullPath: '/icicyta/loa'
      preLoaderRoute: typeof AppIcicytaLoaImport
      parentRoute: typeof AppImport
    }
    '/_app/icicyta/receipt': {
      id: '/_app/icicyta/receipt'
      path: '/icicyta/receipt'
      fullPath: '/icicyta/receipt'
      preLoaderRoute: typeof AppIcicytaReceiptImport
      parentRoute: typeof AppImport
    }
    '/_app/icodsa/invoice': {
      id: '/_app/icodsa/invoice'
      path: '/icodsa/invoice'
      fullPath: '/icodsa/invoice'
      preLoaderRoute: typeof AppIcodsaInvoiceImport
      parentRoute: typeof AppImport
    }
    '/_app/icodsa/loa': {
      id: '/_app/icodsa/loa'
      path: '/icodsa/loa'
      fullPath: '/icodsa/loa'
      preLoaderRoute: typeof AppIcodsaLoaImport
      parentRoute: typeof AppImport
    }
    '/_app/icodsa/receipt': {
      id: '/_app/icodsa/receipt'
      path: '/icodsa/receipt'
      fullPath: '/icodsa/receipt'
      preLoaderRoute: typeof AppIcodsaReceiptImport
      parentRoute: typeof AppImport
    }
  }
}

// Create and export the route tree

interface AppRouteChildren {
  AppBankTransferRoute: typeof AppBankTransferRoute
  AppVirtualAccountsRoute: typeof AppVirtualAccountsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppIcicytaInvoiceRoute: typeof AppIcicytaInvoiceRoute
  AppIcicytaLoaRoute: typeof AppIcicytaLoaRoute
  AppIcicytaReceiptRoute: typeof AppIcicytaReceiptRoute
  AppIcodsaInvoiceRoute: typeof AppIcodsaInvoiceRoute
  AppIcodsaLoaRoute: typeof AppIcodsaLoaRoute
  AppIcodsaReceiptRoute: typeof AppIcodsaReceiptRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBankTransferRoute: AppBankTransferRoute,
  AppVirtualAccountsRoute: AppVirtualAccountsRoute,
  AppIndexRoute: AppIndexRoute,
  AppIcicytaInvoiceRoute: AppIcicytaInvoiceRoute,
  AppIcicytaLoaRoute: AppIcicytaLoaRoute,
  AppIcicytaReceiptRoute: AppIcicytaReceiptRoute,
  AppIcodsaInvoiceRoute: AppIcodsaInvoiceRoute,
  AppIcodsaLoaRoute: AppIcodsaLoaRoute,
  AppIcodsaReceiptRoute: AppIcodsaReceiptRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof AuthRouteWithChildren
  '/bank-transfer': typeof AppBankTransferRoute
  '/virtual-accounts': typeof AppVirtualAccountsRoute
  '/login': typeof AuthLoginRoute
  '/': typeof AppIndexRoute
  '/icicyta/invoice': typeof AppIcicytaInvoiceRoute
  '/icicyta/loa': typeof AppIcicytaLoaRoute
  '/icicyta/receipt': typeof AppIcicytaReceiptRoute
  '/icodsa/invoice': typeof AppIcodsaInvoiceRoute
  '/icodsa/loa': typeof AppIcodsaLoaRoute
  '/icodsa/receipt': typeof AppIcodsaReceiptRoute
}

export interface FileRoutesByTo {
  '': typeof AuthRouteWithChildren
  '/bank-transfer': typeof AppBankTransferRoute
  '/virtual-accounts': typeof AppVirtualAccountsRoute
  '/login': typeof AuthLoginRoute
  '/': typeof AppIndexRoute
  '/icicyta/invoice': typeof AppIcicytaInvoiceRoute
  '/icicyta/loa': typeof AppIcicytaLoaRoute
  '/icicyta/receipt': typeof AppIcicytaReceiptRoute
  '/icodsa/invoice': typeof AppIcodsaInvoiceRoute
  '/icodsa/loa': typeof AppIcodsaLoaRoute
  '/icodsa/receipt': typeof AppIcodsaReceiptRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/bank-transfer': typeof AppBankTransferRoute
  '/_app/virtual-accounts': typeof AppVirtualAccountsRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_app/': typeof AppIndexRoute
  '/_app/icicyta/invoice': typeof AppIcicytaInvoiceRoute
  '/_app/icicyta/loa': typeof AppIcicytaLoaRoute
  '/_app/icicyta/receipt': typeof AppIcicytaReceiptRoute
  '/_app/icodsa/invoice': typeof AppIcodsaInvoiceRoute
  '/_app/icodsa/loa': typeof AppIcodsaLoaRoute
  '/_app/icodsa/receipt': typeof AppIcodsaReceiptRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/bank-transfer'
    | '/virtual-accounts'
    | '/login'
    | '/'
    | '/icicyta/invoice'
    | '/icicyta/loa'
    | '/icicyta/receipt'
    | '/icodsa/invoice'
    | '/icodsa/loa'
    | '/icodsa/receipt'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/bank-transfer'
    | '/virtual-accounts'
    | '/login'
    | '/'
    | '/icicyta/invoice'
    | '/icicyta/loa'
    | '/icicyta/receipt'
    | '/icodsa/invoice'
    | '/icodsa/loa'
    | '/icodsa/receipt'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_app/bank-transfer'
    | '/_app/virtual-accounts'
    | '/_auth/login'
    | '/_app/'
    | '/_app/icicyta/invoice'
    | '/_app/icicyta/loa'
    | '/_app/icicyta/receipt'
    | '/_app/icodsa/invoice'
    | '/_app/icodsa/loa'
    | '/_app/icodsa/receipt'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_app",
        "/_auth"
      ]
    },
    "/_app": {
      "filePath": "_app.tsx",
      "children": [
        "/_app/bank-transfer",
        "/_app/virtual-accounts",
        "/_app/",
        "/_app/icicyta/invoice",
        "/_app/icicyta/loa",
        "/_app/icicyta/receipt",
        "/_app/icodsa/invoice",
        "/_app/icodsa/loa",
        "/_app/icodsa/receipt"
      ]
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/login"
      ]
    },
    "/_app/bank-transfer": {
      "filePath": "_app/bank-transfer.tsx",
      "parent": "/_app"
    },
    "/_app/virtual-accounts": {
      "filePath": "_app/virtual-accounts.tsx",
      "parent": "/_app"
    },
    "/_auth/login": {
      "filePath": "_auth/login.tsx",
      "parent": "/_auth"
    },
    "/_app/": {
      "filePath": "_app/index.tsx",
      "parent": "/_app"
    },
    "/_app/icicyta/invoice": {
      "filePath": "_app/icicyta/invoice.tsx",
      "parent": "/_app"
    },
    "/_app/icicyta/loa": {
      "filePath": "_app/icicyta/loa.tsx",
      "parent": "/_app"
    },
    "/_app/icicyta/receipt": {
      "filePath": "_app/icicyta/receipt.tsx",
      "parent": "/_app"
    },
    "/_app/icodsa/invoice": {
      "filePath": "_app/icodsa/invoice.tsx",
      "parent": "/_app"
    },
    "/_app/icodsa/loa": {
      "filePath": "_app/icodsa/loa.tsx",
      "parent": "/_app"
    },
    "/_app/icodsa/receipt": {
      "filePath": "_app/icodsa/receipt.tsx",
      "parent": "/_app"
    }
  }
}
ROUTE_MANIFEST_END */
